### ISSUE TITLE
Add distance and length units

### ISSUE THREAD

**Issue by nickburt2108** [osmandapp/web#239]
Web version doesn't seem to have ability to convert from km to miles (imperial and US)

**Comment by dmpr0** [comment]
## ToDo

Add support for changing **Units of length** and **Unit of speed**.

# Settings
- [ ] Add **Units of length**
- - [ ] Icon – `ic_action_ruler_unit`
- - [ ] Default value – 
- [ ] Add **Unit of speed**
- - [ ] Icon – `ic_action_speed`
- - [ ] Default value –

**Comment by Zirochkabila** [comment]
# **Testing 1**

## 🟠 Major

- [ ] **1. Miles/feet setting does not affect displayed data.** Issue: Changing the data setting to “Miles/feet” does not affect the display of any data.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/18ab89e9-424f-4321-a08f-207ec6e69121"></video>
<video src="https://github.com/user-attachments/assets/c1e08d38-610b-4d13-bc35-e9bc9957fb3f"></video>
</details>

## 🟡 Minor

- [ ] **1. Text cut off in “Unit of speed” selection.** Issue: When selecting “Nautical miles per hour (knots)”, the “Unit of speed” item is not fully displayed (both names are cut off).

<details><summary>Details</summary>
<img width="800" src="https://github.com/user-attachments/assets/8e6d84dc-c168-4a62-90f0-1401f05cabc2">
</details>

- [ ] **2. Unnecessary dividing line after “Nautical miles per hour (knots)”.** Issue: A dividing line is incorrectly displayed after selecting “Nautical miles per hour (knots)”.

<details><summary>Details</summary>
<img width="800" src="https://github.com/user-attachments/assets/75a64e57-8ca6-4d56-91bb-4f579d19825d">
</details>

- [ ] **3. Incorrect categorization in Units of length.** Issue: Incorrect division into categories in Units of length (red indicates the current state, black is the more logical categorization).

<details><summary>Details</summary>
<img width="800" src="https://github.com/user-attachments/assets/a1165f4f-030f-40d6-ab15-58dfcb50c2da">
</details>

- [ ] **4. Incorrect categorization in Units of speed.** Issue: Incorrect division into categories in Unit of speed (red indicates the current state, and black is the more logical categorization).

<details><summary>Details</summary>
<img width="800" src="https://github.com/user-attachments/assets/1c830d91-4bf4-4ca3-a5e1-adb3a84d5a8b">
</details>

**Comment by dmpr0** [comment]
## UI Review 

- [ ] Use string `unit_of_length`
- [ ] Use string `default_speed_system`

**Comment by Zirochkabila** [comment]
# Testing 2
Checked adding category splits and applying settings to Tracks, Navigation, Plan a Route, Favorites - **Fixed**
