### ISSUE TITLE
Search web

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#432]
## ToDo
* Show categories
* Explore

## Main screen, [Figma](https://www.figma.com/design/vvLQCBSPfJlsVLnTPoCPiw/Web?node-id=1300-85067&m=dev)
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/31ea0d24-051e-4e5d-88fa-c9e6b8db5412"  width="300" height="auto"/> </td>
  </tr>
</table>   

Consist of: 
* Search bar
* Categories
* Explore section

**Search button**

![Screenshot 2024-07-24 at 13 55 33](https://github.com/user-attachments/assets/c0cb44bf-a26c-487d-8a85-8addeb230a21)

- [x] Click should open new Search page

**Categories**
- [x] Show first 6 categories
- [x] Tap on any category should open Search result screen
- [x] Tap on **Show all** should open **Categories** screen

## Categories, [Figma](https://www.figma.com/design/vvLQCBSPfJlsVLnTPoCPiw/Web?node-id=1445-21774&m=dev)

<table style="width:100%">
  <tr>
    <th>Categories</th>
    <th>Filter by name</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5b6ecaef-6671-4972-b869-91dfe9ebd997"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/19f42b55-eae8-49e0-903a-f6350a843cc8"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show full list of predefined categories
- [x] Tap on category should open search screen for selected category
- [ ] Should have separate url search/categories/

## Search results

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c8afa612-a677-4d4d-93da-8134de3a81aa"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show list of search results

### Search bar

<table style="width:100%">
  <tr>
    <th>Default (out of focus)</th>
    <th>Typing</th>
    <th>Out of focus with search phrase</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e9854ed0-228f-41c8-abd8-8c8e91d559e9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/cea2175c-be11-4f21-b459-2fcf2e1e0147"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1cdb4d08-8043-4f71-a2d3-ec4e362d317b"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show **Back** action on the left, tap should open first Search screen
- [x] Show **Clear** action on the right, tap should clear typed text
- [x] Show search phrase
- [x] Search bar should be visible on top while scrolling

### Search item

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4b81f67f-784d-4ac0-86cb-2edf33bab3d7"  width="300" height="auto"/> </td>
  </tr>
</table>   

## Explore

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d1130a64-bf95-4046-a96e-d14214046054"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Shot card with 3 items
- [x] Title `Explore`
- [x] Add **Show all** button
- - [x] Tap should open separate page with url `search/explore/`

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/1c0a1d65-1e81-4f7d-96e3-6887289919ed"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Points from Explore is stays on the map after Search menu was closed.

- - -

**Comment by dmpr0** [comment]
# Review 2
- [ ] Don't show error about location

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Leisure</th>
        <th>Fuel</th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/f70d8ae3-b7df-4433-88be-c69353e952cc"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/user-attachments/assets/238b823b-6c96-4e2e-981f-131fdde42359"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  




- [ ] Search doesn't stop if there is no results in visible map area.

**Comment by dmpr0** [comment]
# Review 3

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9c21c21e-1411-48d9-8657-f2f1d7f7bc4a"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] **Crédit Agricole**  search result is in map center, but distance say it 2km

**Comment by vshcherb** [comment]
- [ ] Can't search toilets directly typing in search box
- [ ] Can't search toilets selecting category in All Categories

**Comment by dmpr0** [comment]
# Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/2f6abe5d-40e4-4b56-adb5-8cbf3f32e391"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/8cbeb92d-df87-49eb-809e-063df67c164c"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/3cf047c3-612d-4377-bad6-3332632745c1"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Search results with filled background
- [ ] Search results without icons

**Comment by vshcherb** [comment]
- [ ] Add space to search query in backend (it's a not live search ui, we request as enter) 
- [ ] Brand search to fix
- [ ] @ivanPyrohivskyi bug search 'silpo ' doesn't find brand 'silpo'
