### ISSUE TITLE
Add support for standard track widths and colors

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/web#522]
### Description
After syncing tracks Android > web, they are displayed not as in mobile version of the app. Track line color and width do not differ from one track to another.
So it is proposed to add support of standard widths and track colors to web version.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/bb806cd3-77cf-4cab-9fae-528bb86dae68"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/9244ae76-5ef6-474a-83f6-ffb4e78c321b"  width="500" height="auto"/> </td>
  </tr>
</table>

### ToDo
Add support of
- [ ] track line colors (standard and if possible custom colors)
- [ ] standard track line widths (thin medium and thick)

**Comment by dmpr0** [comment]
Related to https://github.com/osmandapp/web/issues/481

**Comment by dmpr0** [comment]
## ToDo
New page adds ability to configure track appearance. 

> ! This task should be done after https://github.com/osmandapp/web/issues/543, cause it use the same Color selection components.

## Track menu

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/abcd532c-ebe8-46f4-af0d-7c70a585577d"  width="500" height="auto"/> </td>
  </tr>
</table>   


- [ ] Add Appearance action, icon – 
- - [ ] Click should open separate Appearance page for the selected tracks
- [ ] Add horizontal list of the last 6 used colors to quick pick
- - [ ] Click on color, should apply it to the track and close the menu

## Appearance

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f0b0ed43-68d7-4265-b463-7123b091f3b2"  width="500" height="auto"/> </td>
  </tr>
</table>   

Appearance page will be divided into 4 groups

### Group 1

- [ ] **Direction arrows**
- [ ] **Start/finish icons** 

### Labels, group 2
Probably should be skipped for now, cause the feature is under redesign in Android.


### Color, group 3

### Width, group 4

### Action

- [ ] Add **Reset to default** aciton, icon – `ic_action_reset_to_default_dark`
- [ ] Click should reset track appearance to the default state, before import of before appearance is applied, cause we don't store in the file until export / download
