### ISSUE TITLE
Redesign Add favorite UI

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#543]
## ToDo
> Related
> * #677

## Add / Edit favorite
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/179e6638-2b16-4638-9d4e-d0b078796380"  width="300" height="auto"/> </td>
  </tr>
</table>   

## Map

- [x] Show icon preview with in hover state with big pin, should show selected shape, color, icon

## Name

- [x] Use the same **TextField** component that is already used on the **Login** page.
- [ ] Max 3 lines of text, then enable vertical scroll.

## Address, [Figma](https://www.figma.com/design/fqiiJCrepmJP7XkA3YixSq/My-Places?node-id=192-35319&m=dev)

**State 1:**
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a2a7e229-8faa-486d-8e27-2d68ff6ae623"  width="300" height="auto"/> </td>
  </tr>
</table>  

During automatic address search, right after adding, or when the user clears the text field and clicks the Location icon.

- [x] Label – `Address`
- [x] Primary value – `Searching...`
- [x] Trailing action – Clear field, icon – `ic_action_cancel`

**State 2:**

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1ff1cf61-4e24-43d8-9d0f-6fd1c6c7935c"  width="300" height="auto"/> </td>
  </tr>
</table>  

After the user clears the text field.

- [x] Label – `Address`
- [x] Trailing action – `Auto-fill address`, icon – `ic_action_location_marker_outlined`
- - [x] Add tooltip on hover

**State 3:**

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/68e43299-115d-45dd-af78-b59203b8493d"  width="300" height="auto"/> </td>
  </tr>
</table>  

Filled text field with Address.

- [x] Label – `Address`
- [x] Primary value - typed or automatically determined address.
- [x] Trailing action – Clear field, icon – `ic_action_cancel`

### Empty state:
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8b015db7-55c5-48a8-9a3d-5214ea2c4c62"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Clicking on "Add notes" or the whole item should open the secondary panel.

### Filled state:
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/06a1740f-b8d3-4e89-84db-53f1a5290d0c"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show description preview.
- [x] Limit to max 2 text lines.
- [x] Clicking on the description preview or the whole item should open the secondary panel.

### Secondary panel

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5af865cb-cecc-4377-817b-101400a6efd7"  width="300" height="auto"/> </td>
  </tr>
</table>   

**AppBar**
- [x] Leading action – Back, should close the panel and save user changes.
- [x] Trailing action – Clear description.
- - [x] Icon – `ic_action_close_rounded`

**Body:**

- [x] Try to integrate the simple editor from https://tiptap.dev/

### Item:

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a7febce1-bbe8-448d-9019-0418d7aaab53"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Title – Folder
- [x] Show selected folder name on the right side with `>` icon
- [x] Preselect previously used folder
- [x] Clicking on the Folder item should open the secondary panel

### Secondary panel

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e9a827e2-3445-48a3-94aa-4ecdf401666d"  width="300" height="auto"/> </td>
  </tr>
</table>   

**AppBar**
- [x] Title – `Folders`
- [x] Leading action – Back, should close the panel and save user changes.
- [x] Trailing action – Add folder
- - [x] Icon – `ic_action_folder_add_v2`

**Content:**

- [x] Show list of Favorite folders
- [x] Collapsed by default
- [x] Preselect the last used folder

**Folder item:**
<table style="width:100%">
  <tr>
    <th>Closed</th>
    <th>Open</th>
    <th>Selected</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d16d4448-553d-484f-b8ac-67e43e137373"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/666b2cb1-598e-41ad-bea3-9606a6a0d898"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2d4a3e53-9d2b-4391-91ed-2746c4144afb"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show arrow on the left side if Folder has subfolders.
- - [x] Open state – `ic_action_arrow_down`, color - active
- - [x] Closed state – `ic_action_arrow_up`
- - [x] Clicking should open the list of subfolders.
- [x] Show folder icon – `ic_action_folder`, color should be equal to the color from the file
- [x] Show folder name
- [x] Show quantity of favorite points inside the folder; favorites from subfolders should not be counted.
- [x] Show radio button

**Add folder inside button** 
- [x] Show Add folder button on hover over folder item
- [x] Icon – `ic_action_folder_add_v2`
- [x] Clicking should show the Add folder dialog, with the preselected parent folder.

### Add folder dialog, [Figma](https://www.figma.com/design/fqiiJCrepmJP7XkA3YixSq/My-Places?node-id=222-30086&m=dev)

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/bf6ba5ec-f919-4679-81e3-10c439b499ee"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e35ae6e5-b89f-4e75-bdf4-dad9c964879b"  width="200" height="auto"/> </td>
  </tr>
</table>  

- [x] Text filed for folder name, placeholder New folder
- - [x] Change to Folder name for label
- [x] Location – Dropdown
- - [x] Show folder list on click

**Folder list:**
- [x] Divider first level folder by divider
- [x] Show `↳` before subfolder name
- - [ ] Add 32 dp right padding for each subolder level

# Appearance

- [x] Group title – `Appearance`
- [x] Includes: 
- - [x] Icon
- - [x] Color
- - [x] Shape

**Icon:**
- [x] Title – `Icon`
- [x] Show selected icon on the right side
- [x] Use selected shape and color as background
- [x] Click on item should open Secondary panel for Icon selection

**Color:**
- [x] Title – `Color`
- [x] Show selected color on the right side
- [x] Use selected shape background
- [x] Click on item should open Secondary panel for color selection

**Shape:**
- [x] Title – `Shape`
- [x] Use toggle to select shape
- [x] Use `ic_action_bg_shape_circle` for Circle
- [x] Use `ic_action_bg_shape_square` for Square
- [x] Use `ic_action_bg_shape_octagon` for Octagon

## Icon, secondary panel, [Figma](https://www.figma.com/design/fqiiJCrepmJP7XkA3YixSq/My-Places?node-id=129-102449&m=dev)
<table style="width:100%">
  <tr>
    <th>Secondary panel</th>
    <th>Select group</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e6da2012-21b0-45e3-95c6-e7cf45c7b9be"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2b0db79b-30d8-4af9-ace8-927d82d098ee"  width="300" height="auto"/> </td>
  </tr>
</table>   

**AppBar**
- [x] Title – `All icons`
- [x] Leading action – Back, should close the panel and save user changes.
- [x] Trailing action – Select group
- - [x] Icon – `ic_action_list_flat`
- - [x] Show dropdown with list of all groups, Last used should be first one. 

**Content:**
- [x] Show list available icons, divided by groups
- [x] Last used should be first group
- [x] Highlight selected icon

## Color, secondary panel
<table style="width:100%">
  <tr>
    <th>Secondary panel</th>
    <th>Color menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8a7ecbb9-927c-4222-a6b6-cb31e3f8df07"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ddc861e7-104c-45e4-a71c-2975cf1ecf6b"  width="300" height="auto"/> </td>
  </tr>
</table>   

**AppBar**
- [x] Title – `All colors`
- [x] Leading action – Back, should close the panel and save user changes.
- [x] Trailing action – `Add color`
- - [x] Icon – `ic_action_add`
- - [x] Open `<input type="color">` on click

**Content:**
- [x] Show list of user colors, from `user_palette_default.txt`
- - [x] New colors should be saved there too
- [x] Highlight selected color
- [x] Show color context menu on right-click

**Color context menu:**
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/fe1208b7-1386-49ed-a532-438177a125e5"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] **Edit**, icon – `ic_action_appearance_outlined`
- - [x] Open `<input type="color">` on click
- [x] **Duplicate**, icon – `ic_action_copy`
- - [x] Create color duplicate next to selected
- [x] **Remove**, icon – `ic_action_delete_outlined`
- - [x] Remove color from the list

**Comment by alisa911** [comment]
- Track waypoint editing now shows a live preview pin that updates in real time when changing icon, color, or shape. (test 79)
- Opening a track waypoint from the list now shows a selected pin on the map, and the pin disappears when closing the details panel. (tests 79, 89)
- After adding a favorite from the map, its details panel now opens correctly and closing it with the back button returns to the previous state. (test 85)
- Fixed a bug where adding a favorite while a cloud track was open caused the track to be duplicated on the map after closing the favorite. (test 85)
- Added tests for the new favorite edit UI - covers editing icon, color, shape with preview pin verification, and adding/removing colors from the user's color palette. (test 73)
- Fixed ghost pin reappearing on map after favorite deletion. (test 73)
- Fixed preview pin not disappearing when add-favorite dialog is cancelled. (test 70)
- Fix wpt appearance fallback order (wpt → group → default) and add tests (test 86)

**Comment by alisa911** [comment]
- Fix stale preview marker remaining on map after WptEditPanel closes
- Fix WptEditPanel not resetting when reopened with new favorite data

**Comment by alisa911** [comment]
<img width="943" height="846" alt="Image" src="https://github.com/user-attachments/assets/3287a762-a555-42cd-a4b0-27af3ad0aa2b" />

**Comment by Dane-M-652** [comment]
Folder of a favorite can't be changed anymore:

1. Select a favorite
2. Press "Edit"
3. Click on "Folder"
4. Select a different folder
5. Folder doesn't change in primary panel as expected
6. Press "Save"
7. Favorite remains in previous folder

Thanx for fixing this.

**Comment by alisa911** [comment]
@Dane-M-652 Fixed, thanks for reporting!

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/7e585d24-8ad5-4d72-85d5-c779e1d7bbf5"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Show confirmation dialog after 
- - [x] click on Close button, if there was changes
- - [x] click on any other menu button or icon that leads to closing Add or Edit menu

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/308bec5f-532a-42ae-82cf-eaa4a4da24d2"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Chevrons looks differently
- [x] Right padding should be the same, check Figma

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/220a4666-cca6-471a-a43c-0e5ca0b305b4"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] save button, left / right padding is missing?

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/171b1118-ed05-497f-beb9-83c12659b073"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Different left padding in text fields?

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/2efaef6b-7da1-4a8e-a0cb-89c057606495"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] fix left padding 

- - - - - -
 

- [x] Pin preview should be located in the visible map center
- [x] Move Map center when additional (icon, color) panel is open

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/02bd18f6-38dc-4508-8683-b76341f09ee3"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Don't show `Empty name.` until the Save button is clicked.

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/57c721fa-3e51-4137-abb7-1c8ce765acba"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  
 

- [x] Found a way to prevent password managers to auto complete Name and Address fields

- - - - - -
 
### Folders

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/8452466e-ad5b-4d43-ace9-25d20fc7c8c2"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Folder item should be separated from Apperance
- [x] Use Bold text style for title

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/0e1bc84b-ce0c-4850-9c40-e0a7444c9c8f"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Crash after selecting folder 

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/c1426822-f19d-4482-b56f-4331362db0d9"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/4b910bf8-462e-4f91-9bb1-5f775b899643"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  




- [x] The folder name and label should have a single text size of 16px.
- [x] Are radio buttons default sized? They appear too small. Radio buttons in Dialog are bigger

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/c14b1c92-5938-4db0-bc7e-cbc43c539dd2"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  
 
- [x] Folder item height is 48px

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/1b523b02-8f15-43a5-8fc5-733c8eeec647"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Use Medium text style for Top level folders
- [x] Text size should be the same as in the list = 16 px
- [x] Show list below text field
- [x] Show `— Top level —` as first item
- - [x] Selected by default
- - [x] Creates new folder in the root folder

### Icons

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/91c1cbdd-bf42-494b-b979-154ad67e1566"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Part of the categories are missing

### Colors

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/7160318c-15e6-4725-a5a3-af32c7f859bb"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Unable to save color, probably to free cloud limitations

**Comment by dmpr0** [comment]
## UI Review

- [x] Saving progress shouldn’t cause the entire user interface to move down.

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Result</th>
        <th>Figma</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/891b79a9-15f1-4c5a-a658-b8d6eb8612a2"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/9726286c-07be-4da5-9630-1ec29644c042"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Fix divider length 

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/0ac56217-9f96-432d-b333-8dcebc46ca25"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Show hover over open/close arrow icon on folders

- - - - - -
 

- [x] Description doesn't save as mentioned https://github.com/osmandapp/web/issues/1734

**Comment by Zirochkabila** [comment]
# Testing 1

> Web - prod

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. Add the ability to scroll further down to see the full names of subfolders.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/8af4a960-d05c-4f7a-918b-fb7ade7e43a8"></video>
</details>

* [ ] 2. “Empty name” appears if you click the **Save** button, enter a name, and then delete it.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/09fa8b7a-c85f-438c-8c28-99bfcb9815db"></video>
</details>

**Severity**: 🔵 Trivial / **Priority**: 🔵 Low

* [ ] 1. When the cursor hovers over the last subfolder, an animation glitch occurs.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/29eb44d2-1226-45f1-9af5-152007957bc5"></video>
</details>

* [ ] 2. When quickly scrolling through the categories, items below the list become visible.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/d61ab83c-eb84-4292-9576-b5b70969cf48"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review


<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/efd66cfb-1bcb-400a-8acb-21c7af4e0b27"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

@vshcherb we need to decide how to store HTML tags inside GPX:
```
<desc>&lt;h1&gt;Descripn&lt;/h1&gt;&lt;p&gt;&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Михайлівський собор&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;&lt;s&gt;6 Трьохсвятительська вулиця, Київ&lt;/s&gt;&lt;/p&gt;&lt;p&gt;&lt;a target="_blank" rel="noopener noreferrer nofollow" href="osmand.net"&gt;link&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;/p&gt;
```

or
```
<desc><![CDATA[<h1>Description</h1><p></p><p><strong>Михайлівський собор</strong></p><p><s>6 Трьохсвятительська вулиця, Київ</s></p><p><a target="_blank" rel="noopener noreferrer nofollow" href="https://osmand.net">link</a></p><p></p>]]></desc>
```

**Comment by vshcherb** [comment]
Documentation (gen by AI):
- [Web → Favorites → Appearance](https://osmand.net/docs/user/web/web-favorites#appearance): "icon, color, shape, and icon" repeats *icon*. In *Manage Favorites*, "After registering an OsmAnd Pro and for OsmAnd Start…" needs rewording.
