### ISSUE TITLE
Search issues on OsmAnd web

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/web#597]
### Description
There are 3 issues with web search:
- search for brands doesn't show results on map 
- hover over search results doesn't highlight small POIs (represented on the map as a small circles)
- click on search result doesn't open POI context menu

### Steps to reproduce
First issue (brands)
- go to https://osmand.net/map/search/#13/52.2506/21.0005
- search for Starbucks
- tap the first line in the search results (with "i" icon)

Second issue (hover doesn't highlight POI-circles)
- go to https://osmand.net/map/search/#13/52.2506/21.0005
- search for Starbucks
- hover over various search results 

### Actual result
https://github.com/user-attachments/assets/0aeaf9c0-ecce-4314-9ef6-9d05a8206dce

https://github.com/user-attachments/assets/87ee20d0-5b4b-4ffb-8b5f-df3031dfdffa

### ToDo
- [x] fix brand search (results should be displayed on map)
- [x] hover over all search results should highlight them on map
- [x] click on search result should open POI context menu

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Web</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/478c3b0c-8cbd-44da-8432-6cb8ef3928c6"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/0d93a301-f71d-4de6-a2f0-288b514ec0a5"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] No Brand

**Comment by vshcherb** [comment]
Brand Okko probably related to Starbucks issue - https://overpass-turbo.eu/s/1VoP

**Comment by vshcherb** [comment]
- [ ] Zoom shouldn't change but map should move if search object is not on the map (extreme cases investigate - 1000 km without animation)

**Comment by Zirochkabila** [comment]
# Testing 1
Fixed

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Results for `ОККО` </th>
        <th>Click on brand</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/94269197-5f42-4c5a-8a5c-326b4a695c16"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/730aec9d-654a-4c68-8be3-3b9e7333b4c3"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Tap on brand `ОККО` show no result

**Comment by Zirochkabila** [comment]
# Testing 2
Fixed

**Comment by dmpr0** [comment]
# Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="ttps://github.com/user-attachments/assets/fcdf645d-9620-4a4d-992c-f03223140c84"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/user-attachments/assets/a60f667f-3d9e-4a1d-97dc-0dd26c3ca41f
"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Brand always shows as first result, even after selection
