### ISSUE TITLE
Support track appearance on the map

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/web#711]
### Description

though the same settings, two tracks (see example tracks) are displayed different in the app and online.

In the app (+4.9.9):

![Screenshot_20241210_100119_OsmAnd+](https://github.com/user-attachments/assets/e88c684a-d895-4eb3-9e46-f22505aa4bde)

The same tracks online:

![2024-12-10 online track appearance](https://github.com/user-attachments/assets/74b5aaa2-0bf2-44c9-8a06-754f72a61321)

### Steps to reproduce

I dont know, in the app both tracks do have the same settings

### Actual result

two tracks with the same settings > have online two different colors 

anyway, the track´s app settings don´t "move" to the cloud (like "switched off" start & finish icons, they appear again and fill up the screen)

### Expected result

same color, same settings

### Your Environment (required)

OsmAnd Version: +4.9.9

**Comment by dmpr0** [comment]
## ToDo
Tracks on the should be rendered using track appearance tags:
* Width
* Color
* Start / Finish icons

**Comment by Rowin63** [comment]
So it is supposed to work correctly? 
Right now it does not. 
On the web map all my tracks still are displayed in the same colour.

**Comment by Zirochkabila** [comment]
# Testing 1

The only thing that differs is the width of the line (both when importing from a cloud and when importing from a device - Import tracks button on the WEB)


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Original</th>
    <th>From Cloud</th>
    <th>From Device</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/c85897aa-75ad-4424-a211-84df16b64354"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/bd20f780-76b3-4de0-8a83-32b50ed3f502"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/c4b3a009-6198-4f0d-932c-4a3ba3714098"  width="500" height="auto"/> </th>
  </tr>
</table> 
</details> 


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Original</th>
    <th>From Cloud</th>
    <th>From Device</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/1ff6d58e-8b57-42e7-bd29-d5e48ffcd75b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/9c3398f4-e9d5-4931-918f-cb46158142f3"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/6b125ff4-555d-49b1-9821-089a738615c8"  width="500" height="auto"/> </th>
  </tr>
</table> 
</details>

**Comment by Rowin63** [comment]
> [@Rowin63](https://github.com/Rowin63) Hi. Track appearance support has been added. If you upload a track directly to the web with this tags, everything will display correctly. However, there's currently a bug on Android devices — these tags are lost when the file is saved to the cloud. As a result, tracks loaded from the cloud don't show any appearance settings. [osmandapp/OsmAnd#21798](https://github.com/osmandapp/OsmAnd/issues/21798)

Sorry, I don´t understand if it is fixed or not.
You say, "track appearance support... with tags..." is added.
And in the same sentence you say, there is a bug with this tags and they get lost.

???

**Comment by Rowin63** [comment]
Please explain again, what was solved. because the issue looks as buggy as before.

This is the settings in te app:

![Image](https://github.com/user-attachments/assets/16af47f7-0f7c-4ae2-84db-4d77340b7120)
![Image](https://github.com/user-attachments/assets/e613e1dd-a0ef-49c6-a4dc-32705f1de63d)

And this is how the same tracks are displayed in the web app:

![Image](https://github.com/user-attachments/assets/58861a27-e5a0-425f-90c9-1d378a03c189)

![Image](https://github.com/user-attachments/assets/563b7f23-4c41-45cf-ab60-d97fa67fb65b)

It still is exactly the same as it was, I can´t see any fix.
Both tracks do have the same appearance in the app, but are displayed different in the web map.

**Comment by Rowin63** [comment]
There are differences inside the gpx.
One contains a rte section, the other does not.
One contains lots of code lines in <osmand:routes> and in <osmand:types>, the other does not.

**Comment by Rowin63** [comment]
The answer is:

Tracks which contain <rte> AND <trk> code are displayed in orange color.
Tracks which contain ONLY <trk> code are displayed in blue color.

They´re displayed the same way in the app, but different in the web map.

**Comment by Zirochkabila** [comment]
# **Testing 2**
`OsmAnd~ 5.0.0#4866m, Released: 2025-03-31`

## 🟠 Major
- [ ] **Imported tracks differ from original**  
- **Issue:** When importing from a cloud, the following visual elements are missing or altered compared to the original:

1.   Arrows indicating direction of movement
2.   Track color
3.   Track width

**Test files:** [[Tracks here 3.zip](https://github.com/user-attachments/files/19533563/Archive.3.zip)](https://github.com/user-attachments/files/19533563/Archive.3.zip)

<details><summary>Details</summary>

<table style="width:100%">
  <tr>
    <th>Греція original</th>
    <th>Греція 2 оригінал</th>
    <th>Греція import from cloud</th>
    <th>Греція from file</th>
    <th>Греція 2 import from cloud</th>
    <th>Греція 2 from file</th>
  </tr>
  <tr>
    <th><img src="https://github.com/user-attachments/assets/6530d6c6-cc41-47f1-8085-63bcc71550f8"  width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/b82fdd3a-0792-4ec7-b71c-210e8659265f"  width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/6d9db9df-ea6b-4320-8438-e29a8e39e758"  width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/71a26c74-52ee-461a-bab1-be65c493b3b2"  width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/10023e82-897c-4b4b-b9bd-3bb4c5ee2a3d"  width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/1b770342-f5d6-4953-90ba-03be443af580"  width="300" height="auto"/></th>
  </tr>
</table>

</details>

**Comment by alisa911** [comment]
This tracks don't contain a track appearance section.

**Comment by Rowin63** [comment]
And why they dont? Shouldn´t they?
They have been created in the App and uploaded via cloud sync.

???

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th>24</th>
    <th>Bold</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/fa73f0f4-ae92-4ba7-bd2a-ce8817f3c189"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/df3b18a4-54f2-425b-a042-e3fba47ed5c5"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Width set by numbers doesn't work. 24 is bigger then bold.
* * Tracks - [ParisTracks.zip](https://github.com/user-attachments/files/19549555/ParisTracks.zip)
* * We can set Thin to 1
* * Medium to 3
* * Bold to 9

**Comment by DmitryAlexei** [comment]
Related issue 
https://github.com/osmandapp/OsmAnd/issues/21928

**Comment by alisa911** [comment]
https://github.com/osmandapp/web/issues/711

**Comment by alisa911** [comment]
<img width="577" alt="Image" src="https://github.com/user-attachments/assets/4aaa75cf-ea3c-42c6-8ba6-9001152052ff" />

**Comment by Rowin63** [comment]
> [@Rowin63](https://github.com/Rowin63) Hi. Track appearance support has been added. If you upload a track directly to the web with this tags, everything will display correctly. However, there's currently a bug on Android devices — these tags are lost when the file is saved to the cloud. As a result, tracks loaded from the cloud don't show any appearance settings. [osmandapp/OsmAnd#21798](https://github.com/osmandapp/OsmAnd/issues/21798)

I still don´t understand what was fixed.
What does mean "...If you upload a track directly to the web..."? 
Uploading a track created in the app? 
Or creating a new track online and save it to the cloud then? 
In any case I don´t see any appearance settings. Nothing but a blue line with start and finish icons on display. Like always before, lke from the beginning of this issue.

**Comment by Rowin63** [comment]
The BLUE tracks are good to see.
But the ORANGE routes you need to know where they are, depending on the map content (not possible to change)
"track appearance" on the web is really a must have.

![Image](https://github.com/user-attachments/assets/a3063594-112b-4f1f-9eb9-2cf606c22c93)

![Image](https://github.com/user-attachments/assets/1c6429bc-aad7-4107-bdaf-067ad4836560)

**Comment by Zirochkabila** [comment]
# **Testing 3**
`OsmAnd~ 5.1.0#4947m, Released: 2025-04-07`
`5.0.0.5004`

## 🟠 Major
- [ ] **Incorrect track width rendering for most Android and iOS profiles**
- **Issue:** 8 tracks were created:  
  - **Android:** Thin default, Medium default, Bold default, Custom  
  - **iOS:** thin default, medium default, bold default, custom  

Only the following display the correct width size:
- ✅ iOS custom
- ✅ iOS bold (default)

<details><summary>Details WEB</summary>
<table style="width:100%">
  <tr>
    <th>Android result</th>
    <th>iOS result</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/460f2d9e-5c27-42ab-86bb-f4bf567b84d0"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/62d4e010-23c9-418f-b366-9feb58c41020"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>

<details><summary>Details Android & iOS</summary>
<table style="width:100%">
  <tr>
    <th>Android expected</th>
    <th>iOS expected</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1039c5de-f652-4d2c-a23f-7753c767d3c5"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/6f387abb-beaf-43aa-a76b-f71661c538a7"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
    <th>Web</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/95544d29-c7f4-4a2e-8d85-0f2484caa210"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2a1563e5-49ca-4a2f-bffc-366aad678687"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d3a25bfc-0fb6-4ccf-bb5e-58d0fdf58753"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 4
iOS - `5020`
Android - `OsmAnd~ 5.1.0#5130m, Дата випуску: 2025-05-02`

[Export_02-05-25 iOS.osf.zip](https://github.com/user-attachments/files/20013227/Export_02-05-25.iOS.osf.zip)
[Export_2025-05-02 Android.osf.zip](https://github.com/user-attachments/files/20013226/Export_2025-05-02.Android.osf.zip)

The difference in display is still present (as described in https://github.com/osmandapp/web/issues/781)

<details><summary>Details iOS</summary>
<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Web</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/403bef96-07e4-417a-a16d-15b5ba33532c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/02d04334-498b-494d-8200-d713cfed1268"  width="600" height="auto"/> </th>
  </tr>
</table> 
</details> 

<details><summary>Details Andoid</summary>
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>Web</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/693fd45f-364f-4d2a-9971-22eea1410ed7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/0d77f9fb-6882-41e1-992a-b81097834907"  width="600" height="auto"/> </th>
  </tr>
</table> 
</details>

**Comment by alisa911** [comment]
<img width="912" alt="Image" src="https://github.com/user-attachments/assets/8de8eb41-220b-43ce-9cdd-34e243138171" />

**Comment by alisa911** [comment]
<img width="926" alt="Image" src="https://github.com/user-attachments/assets/882d3e59-83e4-43e4-b31e-81bb4a4b5a30" />

**Comment by dmpr0** [comment]
## UI Review

- [ ] Support `ARGB`. Android and iOS used it for GPX and Favorite colors.

**Comment by alisa911** [comment]
<img width="1215" alt="Image" src="https://github.com/user-attachments/assets/328f1510-9d35-4493-93b1-331e128fd97b" />

**Comment by Zirochkabila** [comment]
# **Testing 5**

`5.0.3.5021`
`OsmAnd~ 5.1.0#5147m, Released: 2025-05-07`

[Export\_2025-05-07 Android.osf.zip](https://github.com/user-attachments/files/20087356/Export_2025-05-07.Android.osf.zip)
[Export\_07-05-25 iOS.osf.zip](https://github.com/user-attachments/files/20087355/Export_07-05-25.iOS.osf.zip)

## 🟠 Major

* [ ] **1. Inconsistencies in visual representation of the same .osf track between Android, iOS and Web**

**iOS > Web**:

* Different colors used
* Directional arrows are missing
* Line thickness does not reflect differences between "thin" and "medium" styles

**Android > Web**:

* Line thickness does not reflect differences between "thin" and "medium" styles

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>Web - result</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/cffe0968-d391-45fc-9e85-5d156e2f90e9"  width="300" height="auto"/></td>
    <td><img src="https://github.com/user-attachments/assets/00f070d6-82ae-4c10-a833-98d84d5bdd5a"  width="700" height="auto"/></td>
    <td><img src="https://github.com/user-attachments/assets/c0f9b78c-8bc3-46b4-964f-4c14670134d9"  width="600" height="auto"/></td>
  </tr>
</table>
</details>

**Comment by alisa911** [comment]
> # **Testing 5**
> `5.0.3.5021` `OsmAnd~ 5.1.0#5147m, Released: 2025-05-07`
> 
> [Export_2025-05-07 Android.osf.zip](https://github.com/user-attachments/files/20087356/Export_2025-05-07.Android.osf.zip) [Export_07-05-25 iOS.osf.zip](https://github.com/user-attachments/files/20087355/Export_07-05-25.iOS.osf.zip)
> 
> ## 🟠 Major
> * [ ]  **1. Inconsistencies in visual representation of the same .osf track between Android, iOS and Web**
> 
> **iOS > Web (Cloud)**:
> 
> * Different colors used
> * Directional arrows are missing
> * Line thickness does not reflect differences between "thin" and "medium" styles
> 
> **Android > Web (Cloud)**:
> 
> * Line thickness does not reflect differences between "thin" and "medium" styles
> 
> Details

- [ ] iOS tracks without .info files don't apply custom track appearance
- [ ] The line thickness on the web approved by @dmpr0

**Comment by Zirochkabila** [comment]
# ReTesting 5

<details><summary>Fixed - Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f8323b2b-89d8-4aab-9ab5-6edb0ce84688"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/8865aba9-ebe7-486a-b7f0-8f45e73885e2"  width="700" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d8984903-a634-4388-b9f5-6caebc406701"  width="300" height="auto"/> </th>
  </tr>
</table> 
</details>
